#pragma once

#define NO_DISPLAY 0

enum KeyType
{
    NOT_IMPLEMENTED = 0,
    PRINTABLE,
	CONTROL,
    MODIFIER,
    LOCK,
	NAVIGATION,
	NUMPAD,
    FUNCTION,
	SPECIAL
};

struct KeyMapValue
{
    unsigned char ascii;
    enum KeyType type;
};

struct KeyMapValue keycode_ascii[256] =
{
    [KEY_NONE] = { NO_DISPLAY, SPECIAL },

    /* 1–0 */
    [KEY_1_PRESSED] = { '1', PRINTABLE }, [KEY_1_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_2_PRESSED] = { '2', PRINTABLE }, [KEY_2_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_3_PRESSED] = { '3', PRINTABLE }, [KEY_3_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_4_PRESSED] = { '4', PRINTABLE }, [KEY_4_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_5_PRESSED] = { '5', PRINTABLE }, [KEY_5_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_6_PRESSED] = { '6', PRINTABLE }, [KEY_6_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_7_PRESSED] = { '7', PRINTABLE }, [KEY_7_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_8_PRESSED] = { '8', PRINTABLE }, [KEY_8_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_9_PRESSED] = { '9', PRINTABLE }, [KEY_9_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_0_PRESSED] = { '0', PRINTABLE }, [KEY_0_RELEASED] = { NO_DISPLAY, PRINTABLE },

    /* A–Z */
    [KEY_A_PRESSED] = { 'a', PRINTABLE }, [KEY_A_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_B_PRESSED] = { 'b', PRINTABLE }, [KEY_B_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_C_PRESSED] = { 'c', PRINTABLE }, [KEY_C_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_D_PRESSED] = { 'd', PRINTABLE }, [KEY_D_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_E_PRESSED] = { 'e', PRINTABLE }, [KEY_E_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_F_PRESSED] = { 'f', PRINTABLE }, [KEY_F_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_G_PRESSED] = { 'g', PRINTABLE }, [KEY_G_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_H_PRESSED] = { 'h', PRINTABLE }, [KEY_H_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_I_PRESSED] = { 'i', PRINTABLE }, [KEY_I_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_J_PRESSED] = { 'j', PRINTABLE }, [KEY_J_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_K_PRESSED] = { 'k', PRINTABLE }, [KEY_K_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_L_PRESSED] = { 'l', PRINTABLE }, [KEY_L_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_M_PRESSED] = { 'm', PRINTABLE }, [KEY_M_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_N_PRESSED] = { 'n', PRINTABLE }, [KEY_N_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_O_PRESSED] = { 'o', PRINTABLE }, [KEY_O_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_P_PRESSED] = { 'p', PRINTABLE }, [KEY_P_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_Q_PRESSED] = { 'q', PRINTABLE }, [KEY_Q_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_R_PRESSED] = { 'r', PRINTABLE }, [KEY_R_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_S_PRESSED] = { 's', PRINTABLE }, [KEY_S_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_T_PRESSED] = { 't', PRINTABLE }, [KEY_T_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_U_PRESSED] = { 'u', PRINTABLE }, [KEY_U_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_V_PRESSED] = { 'v', PRINTABLE }, [KEY_V_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_W_PRESSED] = { 'w', PRINTABLE }, [KEY_W_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_X_PRESSED] = { 'x', PRINTABLE }, [KEY_X_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_Y_PRESSED] = { 'y', PRINTABLE }, [KEY_Y_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_Z_PRESSED] = { 'z', PRINTABLE }, [KEY_Z_RELEASED] = { NO_DISPLAY, PRINTABLE },

    /* space */
    [KEY_SPACE_PRESSED] = { ' ', PRINTABLE }, [KEY_SPACE_RELEASED] = { NO_DISPLAY, PRINTABLE },

    /* symbols */
    [KEY_GRAVE_PRESSED]      = { '`',  PRINTABLE }, [KEY_GRAVE_RELEASED]      = { NO_DISPLAY, PRINTABLE },
    [KEY_MINUS_PRESSED]      = { '-',  PRINTABLE }, [KEY_MINUS_RELEASED]      = { NO_DISPLAY, PRINTABLE },
    [KEY_EQUALS_PRESSED]     = { '=',  PRINTABLE }, [KEY_EQUALS_RELEASED]     = { NO_DISPLAY, PRINTABLE },
    [KEY_LBRACKET_PRESSED]   = { '[',  PRINTABLE }, [KEY_LBRACKET_RELEASED]   = { NO_DISPLAY, PRINTABLE },
    [KEY_RBRACKET_PRESSED]   = { ']',  PRINTABLE }, [KEY_RBRACKET_RELEASED]   = { NO_DISPLAY, PRINTABLE },
    [KEY_BACKSLASH_PRESSED]  = { '\\', PRINTABLE }, [KEY_BACKSLASH_RELEASED]  = { NO_DISPLAY, PRINTABLE },
    [KEY_SEMICOLON_PRESSED]  = { ';',  PRINTABLE }, [KEY_SEMICOLON_RELEASED]  = { NO_DISPLAY, PRINTABLE },
    [KEY_APOSTROPHE_PRESSED] = { '\'', PRINTABLE }, [KEY_APOSTROPHE_RELEASED] = { NO_DISPLAY, PRINTABLE },
    [KEY_COMMA_PRESSED]      = { ',',  PRINTABLE }, [KEY_COMMA_RELEASED]      = { NO_DISPLAY, PRINTABLE },
    [KEY_DOT_PRESSED]        = { '.',  PRINTABLE }, [KEY_DOT_RELEASED]        = { NO_DISPLAY, PRINTABLE },
    [KEY_SLASH_PRESSED]      = { '/',  PRINTABLE }, [KEY_SLASH_RELEASED]      = { NO_DISPLAY, PRINTABLE },

    /* control */
    [KEY_ESCAPE_PRESSED]     = { 27,   CONTROL }, [KEY_ESCAPE_RELEASED]     = { NO_DISPLAY, CONTROL },
    [KEY_TAB_PRESSED]        = { '\t', CONTROL }, [KEY_TAB_RELEASED]        = { NO_DISPLAY, CONTROL },
    [KEY_BACKSPACE_PRESSED]  = { '\b', CONTROL }, [KEY_BACKSPACE_RELEASED]  = { NO_DISPLAY, CONTROL },
    [KEY_ENTER_PRESSED]      = { '\n', CONTROL }, [KEY_ENTER_RELEASED]      = { NO_DISPLAY, CONTROL },
    [KEY_INSERT_PRESSED]     = { NO_DISPLAY, CONTROL }, [KEY_INSERT_RELEASED] = { NO_DISPLAY, CONTROL },
    [KEY_DELETE_PRESSED]     = { 127, CONTROL }, [KEY_DELETE_RELEASED]     = { NO_DISPLAY, CONTROL },

    /* modifiers */
    [KEY_LSHIFT_PRESSED] = { NO_DISPLAY, MODIFIER }, [KEY_LSHIFT_RELEASED] = { NO_DISPLAY, MODIFIER },
    [KEY_RSHIFT_PRESSED] = { NO_DISPLAY, MODIFIER }, [KEY_RSHIFT_RELEASED] = { NO_DISPLAY, MODIFIER },
    [KEY_LCTRL_PRESSED]  = { NO_DISPLAY, MODIFIER }, [KEY_LCTRL_RELEASED]  = { NO_DISPLAY, MODIFIER },
    [KEY_RCTRL_PRESSED]  = { NO_DISPLAY, MODIFIER }, [KEY_RCTRL_RELEASED]  = { NO_DISPLAY, MODIFIER },
    [KEY_LALT_PRESSED]   = { NO_DISPLAY, MODIFIER }, [KEY_LALT_RELEASED]   = { NO_DISPLAY, MODIFIER },
    [KEY_RALT_PRESSED]   = { NO_DISPLAY, MODIFIER }, [KEY_RALT_RELEASED]   = { NO_DISPLAY, MODIFIER },

    /* locks */
    [KEY_CAPSLOCK_PRESSED]   = { NO_DISPLAY, LOCK }, [KEY_CAPSLOCK_RELEASED]   = { NO_DISPLAY, LOCK },
    [KEY_NUMLOCK_PRESSED]    = { NO_DISPLAY, LOCK }, [KEY_NUMLOCK_RELEASED]    = { NO_DISPLAY, LOCK },
    [KEY_SCROLLLOCK_PRESSED] = { NO_DISPLAY, LOCK }, [KEY_SCROLLLOCK_RELEASED] = { NO_DISPLAY, LOCK },

    /* navigation */
    [KEY_UP_PRESSED]        = { NO_DISPLAY, NAVIGATION }, [KEY_UP_RELEASED]        = { NO_DISPLAY, NAVIGATION },
    [KEY_DOWN_PRESSED]      = { NO_DISPLAY, NAVIGATION }, [KEY_DOWN_RELEASED]      = { NO_DISPLAY, NAVIGATION },
    [KEY_LEFT_PRESSED]      = { NO_DISPLAY, NAVIGATION }, [KEY_LEFT_RELEASED]      = { NO_DISPLAY, NAVIGATION },
    [KEY_RIGHT_PRESSED]     = { NO_DISPLAY, NAVIGATION }, [KEY_RIGHT_RELEASED]     = { NO_DISPLAY, NAVIGATION },
    [KEY_HOME_PRESSED]      = { NO_DISPLAY, NAVIGATION }, [KEY_HOME_RELEASED]      = { NO_DISPLAY, NAVIGATION },
    [KEY_END_PRESSED]       = { NO_DISPLAY, NAVIGATION }, [KEY_END_RELEASED]       = { NO_DISPLAY, NAVIGATION },
    [KEY_PAGE_UP_PRESSED]   = { NO_DISPLAY, NAVIGATION }, [KEY_PAGE_UP_RELEASED]   = { NO_DISPLAY, NAVIGATION },
    [KEY_PAGE_DOWN_PRESSED] = { NO_DISPLAY, NAVIGATION }, [KEY_PAGE_DOWN_RELEASED] = { NO_DISPLAY, NAVIGATION },

    /* numpad 1–0 */
    [KEY_NP_1_PRESSED] = { '1', NUMPAD }, [KEY_NP_1_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_2_PRESSED] = { '2', NUMPAD }, [KEY_NP_2_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_3_PRESSED] = { '3', NUMPAD }, [KEY_NP_3_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_4_PRESSED] = { '4', NUMPAD }, [KEY_NP_4_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_5_PRESSED] = { '5', NUMPAD }, [KEY_NP_5_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_6_PRESSED] = { '6', NUMPAD }, [KEY_NP_6_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_7_PRESSED] = { '7', NUMPAD }, [KEY_NP_7_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_8_PRESSED] = { '8', NUMPAD }, [KEY_NP_8_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_9_PRESSED] = { '9', NUMPAD }, [KEY_NP_9_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_0_PRESSED] = { '0', NUMPAD }, [KEY_NP_0_RELEASED] = { NO_DISPLAY, NUMPAD },

    /* numpad ops */
    [KEY_NP_DOT_PRESSED]   = { '.', NUMPAD }, [KEY_NP_DOT_RELEASED]   = { NO_DISPLAY, NUMPAD },
    [KEY_NP_SLASH_PRESSED] = { '/', NUMPAD }, [KEY_NP_SLASH_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_STAR_PRESSED]  = { '*', NUMPAD }, [KEY_NP_STAR_RELEASED]  = { NO_DISPLAY, NUMPAD },
    [KEY_NP_MINUS_PRESSED] = { '-', NUMPAD }, [KEY_NP_MINUS_RELEASED] = { NO_DISPLAY, NUMPAD },
    [KEY_NP_PLUS_PRESSED]  = { '+', NUMPAD }, [KEY_NP_PLUS_RELEASED]  = { NO_DISPLAY, NUMPAD },
    [KEY_NP_ENTER_PRESSED] = { '\n', NUMPAD }, [KEY_NP_ENTER_RELEASED] = { NO_DISPLAY, NUMPAD },

    /* function keys */
    [KEY_F1_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F1_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F2_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F2_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F3_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F3_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F4_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F4_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F5_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F5_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F6_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F6_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F7_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F7_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F8_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F8_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F9_PRESSED]  = { NO_DISPLAY, FUNCTION }, [KEY_F9_RELEASED]  = { NO_DISPLAY, FUNCTION },
    [KEY_F10_PRESSED] = { NO_DISPLAY, FUNCTION }, [KEY_F10_RELEASED] = { NO_DISPLAY, FUNCTION },
    [KEY_F11_PRESSED] = { NO_DISPLAY, FUNCTION }, [KEY_F11_RELEASED] = { NO_DISPLAY, FUNCTION },
    [KEY_F12_PRESSED] = { NO_DISPLAY, FUNCTION }, [KEY_F12_RELEASED] = { NO_DISPLAY, FUNCTION },

    /* misc */
    [KEY_LGUI_PRESSED]           = { NO_DISPLAY, SPECIAL },  [KEY_LGUI_RELEASED]           = { NO_DISPLAY, SPECIAL },
    [KEY_RGUI_PRESSED]           = { NO_DISPLAY, SPECIAL },  [KEY_RGUI_RELEASED]           = { NO_DISPLAY, SPECIAL },
    [KEY_APPS_PRESSED]           = { NO_DISPLAY, SPECIAL },  [KEY_APPS_RELEASED]           = { NO_DISPLAY, SPECIAL },
    [KEY_PREV_TRACK_PRESSED]     = { NO_DISPLAY, SPECIAL },  [KEY_PREV_TRACK_RELEASED]     = { NO_DISPLAY, SPECIAL },
    [KEY_NEXT_TRACK_PRESSED]     = { NO_DISPLAY, SPECIAL },  [KEY_NEXT_TRACK_RELEASED]     = { NO_DISPLAY, SPECIAL },
    [KEY_PLAY_PRESSED]           = { NO_DISPLAY, SPECIAL },  [KEY_PLAY_RELEASED]           = { NO_DISPLAY, SPECIAL },
    [KEY_STOP_PRESSED]           = { NO_DISPLAY, SPECIAL },  [KEY_STOP_RELEASED]           = { NO_DISPLAY, SPECIAL },
    [KEY_MUTE_PRESSED]           = { NO_DISPLAY, SPECIAL },  [KEY_MUTE_RELEASED]           = { NO_DISPLAY, SPECIAL },
    [KEY_VOL_DOWN_PRESSED]       = { NO_DISPLAY, SPECIAL },  [KEY_VOL_DOWN_RELEASED]       = { NO_DISPLAY, SPECIAL },
    [KEY_VOL_UP_PRESSED]         = { NO_DISPLAY, SPECIAL },  [KEY_VOL_UP_RELEASED]         = { NO_DISPLAY, SPECIAL },
    [KEY_MEDIA_SELECT_PRESSED]   = { NO_DISPLAY, SPECIAL },  [KEY_MEDIA_SELECT_RELEASED]   = { NO_DISPLAY, SPECIAL },
    [KEY_CALCULATOR_PRESSED]     = { NO_DISPLAY, SPECIAL },  [KEY_CALCULATOR_RELEASED]     = { NO_DISPLAY, SPECIAL },
    [KEY_MY_COMPUTER_PRESSED]    = { NO_DISPLAY, SPECIAL },  [KEY_MY_COMPUTER_RELEASED]    = { NO_DISPLAY, SPECIAL },
    [KEY_EMAIL_PRESSED]          = { NO_DISPLAY, SPECIAL },  [KEY_EMAIL_RELEASED]          = { NO_DISPLAY, SPECIAL },
    [KEY_WWW_HOME_PRESSED]       = { NO_DISPLAY, SPECIAL },  [KEY_WWW_HOME_RELEASED]       = { NO_DISPLAY, SPECIAL },
    [KEY_WWW_SEARCH_PRESSED]     = { NO_DISPLAY, SPECIAL },  [KEY_WWW_SEARCH_RELEASED]     = { NO_DISPLAY, SPECIAL },
    [KEY_WWW_FAVORITES_PRESSED]  = { NO_DISPLAY, SPECIAL },  [KEY_WWW_FAVORITES_RELEASED]  = { NO_DISPLAY, SPECIAL },
    [KEY_WWW_REFRESH_PRESSED]    = { NO_DISPLAY, SPECIAL },  [KEY_WWW_REFRESH_RELEASED]    = { NO_DISPLAY, SPECIAL },
    [KEY_WWW_STOP_PRESSED]       = { NO_DISPLAY, SPECIAL },  [KEY_WWW_STOP_RELEASED]       = { NO_DISPLAY, SPECIAL },
    [KEY_WWW_FORWARD_PRESSED]    = { NO_DISPLAY, SPECIAL },  [KEY_WWW_FORWARD_RELEASED]    = { NO_DISPLAY, SPECIAL },
    [KEY_WWW_BACK_PRESSED]       = { NO_DISPLAY, SPECIAL },  [KEY_WWW_BACK_RELEASED]       = { NO_DISPLAY, SPECIAL },
    [KEY_ACPI_POWER_PRESSED]     = { NO_DISPLAY, SPECIAL },  [KEY_ACPI_POWER_RELEASED]     = { NO_DISPLAY, SPECIAL },
    [KEY_ACPI_SLEEP_PRESSED]     = { NO_DISPLAY, SPECIAL },  [KEY_ACPI_SLEEP_RELEASED]     = { NO_DISPLAY, SPECIAL },
    [KEY_ACPI_WAKE_PRESSED]      = { NO_DISPLAY, SPECIAL },  [KEY_ACPI_WAKE_RELEASED]      = { NO_DISPLAY, SPECIAL },
};

char shift_map[128] = {
    ['1'] = '!',  ['2'] = '@',  ['3'] = '#',  ['4'] = '$',  ['5'] = '%',
    ['6'] = '^',  ['7'] = '&',  ['8'] = '*',  ['9'] = '(',  ['0'] = ')',

    ['-'] = '_',  ['='] = '+',  ['['] = '{',  [']'] = '}',  [' '] = ' ',
    [';'] = ':',  [','] = '<',  ['.'] = '>',  ['/'] = '?',  ['`'] = '~',
    ['\''] = '"', ['\\'] = '|',
};
