#ifndef OS_KEYCODE_H
#define OS_KEYCODE_H

enum keycode
{
  KEY_NONE = 0,

  /* 1–0 */
  KEY_1_PRESSED, KEY_1_RELEASED,
  KEY_2_PRESSED, KEY_2_RELEASED,
  KEY_3_PRESSED, KEY_3_RELEASED,
  KEY_4_PRESSED, KEY_4_RELEASED,
  KEY_5_PRESSED, KEY_5_RELEASED,
  KEY_6_PRESSED, KEY_6_RELEASED,
  KEY_7_PRESSED, KEY_7_RELEASED,
  KEY_8_PRESSED, KEY_8_RELEASED,
  KEY_9_PRESSED, KEY_9_RELEASED,
  KEY_0_PRESSED, KEY_0_RELEASED,

  /* A–Z */
  KEY_A_PRESSED, KEY_A_RELEASED,
  KEY_B_PRESSED, KEY_B_RELEASED,
  KEY_C_PRESSED, KEY_C_RELEASED,
  KEY_D_PRESSED, KEY_D_RELEASED,
  KEY_E_PRESSED, KEY_E_RELEASED,
  KEY_F_PRESSED, KEY_F_RELEASED,
  KEY_G_PRESSED, KEY_G_RELEASED,
  KEY_H_PRESSED, KEY_H_RELEASED,
  KEY_I_PRESSED, KEY_I_RELEASED,
  KEY_J_PRESSED, KEY_J_RELEASED,
  KEY_K_PRESSED, KEY_K_RELEASED,
  KEY_L_PRESSED, KEY_L_RELEASED,
  KEY_M_PRESSED, KEY_M_RELEASED,
  KEY_N_PRESSED, KEY_N_RELEASED,
  KEY_O_PRESSED, KEY_O_RELEASED,
  KEY_P_PRESSED, KEY_P_RELEASED,
  KEY_Q_PRESSED, KEY_Q_RELEASED,
  KEY_R_PRESSED, KEY_R_RELEASED,
  KEY_S_PRESSED, KEY_S_RELEASED,
  KEY_T_PRESSED, KEY_T_RELEASED,
  KEY_U_PRESSED, KEY_U_RELEASED,
  KEY_V_PRESSED, KEY_V_RELEASED,
  KEY_W_PRESSED, KEY_W_RELEASED,
  KEY_X_PRESSED, KEY_X_RELEASED,
  KEY_Y_PRESSED, KEY_Y_RELEASED,
  KEY_Z_PRESSED, KEY_Z_RELEASED,

  /* space */
  KEY_SPACE_PRESSED, KEY_SPACE_RELEASED,

  /* symbols */
  KEY_GRAVE_PRESSED, KEY_GRAVE_RELEASED,
  KEY_MINUS_PRESSED, KEY_MINUS_RELEASED,
  KEY_EQUALS_PRESSED, KEY_EQUALS_RELEASED,
  KEY_LBRACKET_PRESSED, KEY_LBRACKET_RELEASED,
  KEY_RBRACKET_PRESSED, KEY_RBRACKET_RELEASED,
  KEY_BACKSLASH_PRESSED, KEY_BACKSLASH_RELEASED,
  KEY_SEMICOLON_PRESSED, KEY_SEMICOLON_RELEASED,
  KEY_APOSTROPHE_PRESSED, KEY_APOSTROPHE_RELEASED,
  KEY_COMMA_PRESSED, KEY_COMMA_RELEASED,
  KEY_DOT_PRESSED, KEY_DOT_RELEASED,
  KEY_SLASH_PRESSED, KEY_SLASH_RELEASED,

  /* control */
  KEY_ESCAPE_PRESSED, KEY_ESCAPE_RELEASED,
  KEY_TAB_PRESSED, KEY_TAB_RELEASED,
  KEY_BACKSPACE_PRESSED, KEY_BACKSPACE_RELEASED,
  KEY_ENTER_PRESSED, KEY_ENTER_RELEASED,
  KEY_INSERT_PRESSED, KEY_INSERT_RELEASED,
  KEY_DELETE_PRESSED, KEY_DELETE_RELEASED,

  /* modifiers */
  KEY_LSHIFT_PRESSED, KEY_LSHIFT_RELEASED,
  KEY_RSHIFT_PRESSED, KEY_RSHIFT_RELEASED,
  KEY_LCTRL_PRESSED, KEY_LCTRL_RELEASED,
  KEY_RCTRL_PRESSED, KEY_RCTRL_RELEASED,
  KEY_LALT_PRESSED, KEY_LALT_RELEASED,
  KEY_RALT_PRESSED, KEY_RALT_RELEASED,

  /* locks */
  KEY_CAPSLOCK_PRESSED, KEY_CAPSLOCK_RELEASED,
  KEY_NUMLOCK_PRESSED, KEY_NUMLOCK_RELEASED,
  KEY_SCROLLLOCK_PRESSED, KEY_SCROLLLOCK_RELEASED,

  /* navigation */
  KEY_UP_PRESSED, KEY_UP_RELEASED,
  KEY_DOWN_PRESSED, KEY_DOWN_RELEASED,
  KEY_LEFT_PRESSED, KEY_LEFT_RELEASED,
  KEY_RIGHT_PRESSED, KEY_RIGHT_RELEASED,
  KEY_HOME_PRESSED, KEY_HOME_RELEASED,
  KEY_END_PRESSED, KEY_END_RELEASED,
  KEY_PAGE_UP_PRESSED, KEY_PAGE_UP_RELEASED,
  KEY_PAGE_DOWN_PRESSED, KEY_PAGE_DOWN_RELEASED,

  /* numpad 1–0 */
  KEY_NP_1_PRESSED, KEY_NP_1_RELEASED,
  KEY_NP_2_PRESSED, KEY_NP_2_RELEASED,
  KEY_NP_3_PRESSED, KEY_NP_3_RELEASED,
  KEY_NP_4_PRESSED, KEY_NP_4_RELEASED,
  KEY_NP_5_PRESSED, KEY_NP_5_RELEASED,
  KEY_NP_6_PRESSED, KEY_NP_6_RELEASED,
  KEY_NP_7_PRESSED, KEY_NP_7_RELEASED,
  KEY_NP_8_PRESSED, KEY_NP_8_RELEASED,
  KEY_NP_9_PRESSED, KEY_NP_9_RELEASED,
  KEY_NP_0_PRESSED, KEY_NP_0_RELEASED,

  /* numpad ops */
  KEY_NP_DOT_PRESSED, KEY_NP_DOT_RELEASED,
  KEY_NP_SLASH_PRESSED, KEY_NP_SLASH_RELEASED,
  KEY_NP_STAR_PRESSED, KEY_NP_STAR_RELEASED,
  KEY_NP_MINUS_PRESSED, KEY_NP_MINUS_RELEASED,
  KEY_NP_PLUS_PRESSED, KEY_NP_PLUS_RELEASED,
  KEY_NP_ENTER_PRESSED, KEY_NP_ENTER_RELEASED,

  /* function keys */
  KEY_F1_PRESSED, KEY_F1_RELEASED,
  KEY_F2_PRESSED, KEY_F2_RELEASED,
  KEY_F3_PRESSED, KEY_F3_RELEASED,
  KEY_F4_PRESSED, KEY_F4_RELEASED,
  KEY_F5_PRESSED, KEY_F5_RELEASED,
  KEY_F6_PRESSED, KEY_F6_RELEASED,
  KEY_F7_PRESSED, KEY_F7_RELEASED,
  KEY_F8_PRESSED, KEY_F8_RELEASED,
  KEY_F9_PRESSED, KEY_F9_RELEASED,
  KEY_F10_PRESSED, KEY_F10_RELEASED,
  KEY_F11_PRESSED, KEY_F11_RELEASED,
  KEY_F12_PRESSED, KEY_F12_RELEASED,

  /* misc */
  KEY_LGUI_PRESSED, KEY_LGUI_RELEASED,
  KEY_RGUI_PRESSED, KEY_RGUI_RELEASED,
  KEY_APPS_PRESSED, KEY_APPS_RELEASED,
  KEY_PREV_TRACK_PRESSED, KEY_PREV_TRACK_RELEASED,
  KEY_NEXT_TRACK_PRESSED, KEY_NEXT_TRACK_RELEASED,
  KEY_PLAY_PRESSED, KEY_PLAY_RELEASED,
  KEY_STOP_PRESSED, KEY_STOP_RELEASED,
  KEY_MUTE_PRESSED, KEY_MUTE_RELEASED,
  KEY_VOL_DOWN_PRESSED, KEY_VOL_DOWN_RELEASED,
  KEY_VOL_UP_PRESSED, KEY_VOL_UP_RELEASED,
  KEY_MEDIA_SELECT_PRESSED, KEY_MEDIA_SELECT_RELEASED,
  KEY_CALCULATOR_PRESSED, KEY_CALCULATOR_RELEASED,
  KEY_MY_COMPUTER_PRESSED, KEY_MY_COMPUTER_RELEASED,
  KEY_EMAIL_PRESSED, KEY_EMAIL_RELEASED,
  KEY_WWW_HOME_PRESSED, KEY_WWW_HOME_RELEASED,
  KEY_WWW_SEARCH_PRESSED, KEY_WWW_SEARCH_RELEASED,
  KEY_WWW_FAVORITES_PRESSED, KEY_WWW_FAVORITES_RELEASED,
  KEY_WWW_REFRESH_PRESSED, KEY_WWW_REFRESH_RELEASED,
  KEY_WWW_STOP_PRESSED, KEY_WWW_STOP_RELEASED,
  KEY_WWW_FORWARD_PRESSED, KEY_WWW_FORWARD_RELEASED,
  KEY_WWW_BACK_PRESSED, KEY_WWW_BACK_RELEASED,
  KEY_ACPI_POWER_PRESSED, KEY_ACPI_POWER_RELEASED,
  KEY_ACPI_SLEEP_PRESSED, KEY_ACPI_SLEEP_RELEASED,
  KEY_ACPI_WAKE_PRESSED, KEY_ACPI_WAKE_RELEASED,

};

#endif